server:
  port: 9800

spring:
  redis:
    port: 6379
    host: localhost
    # Redis服务器连接密码
    password: 123456
    # Redis数据库索引（默认为0）
    database: 0
    #连接池最大连接数（使用负值表示没有限制）
    lettuce:
      pool:
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 0
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
    # 连接超时时间（毫秒）
    timeout: 5000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/oomall?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: gooda
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
      test-while-idle: true

  cloud:
    nacos:
      server-addr: localhost:8848

  application:
    name: oomall-freight

management:
  endpoints:
    web:
      exposure:
        include: '*'

dubbo:

  application:
    name: dubbo-freight
  scan:
    base-packages: cn.edu.xmu.oomall.service
  registry:
#    address: nacos://localhost:8848
    address: nacos://47.115.162.144:8848
  protocol:
    name: dubbo
    port: 19800

oomall:
  external:
    goods-service:
      name: SimulatedGoodsServiceImpl

  strategy:
    freight-calculate:
      name: FreightCalculateImpl

  goods:
    version: 0.0.1-SNAPSHOT

  freight:
    #模式
    model:
      #重量运费模式
      weight: 0
      #计件运费模式
      piece: 1

  redis:
    prifix: freight

    delimiter: _

  #kg
  kg: 1000
  #0.5kg
  half-kg: 500
  #10
  ten: 10
  #50
  fifty: 50
  #100
  hundry: 100
  #300
  tri-hundry: 300



