server:
  port: 9900

spring:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/oomall?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: gooda
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
      test-while-idle: true

  cloud:
    nacos:
      server-addr: localhost:8848

  application:
    name: oomall-order

management:
  endpoints:
    web:
      exposure:
        include: '*'

dubbo:
  application:
    name: dubbo-order
  scan:
    base-packages: cn.edu.xmu.oomall.service
  registry:
    address: nacos://localhost:8848
  protocol:
    name: dubbo
    port: 19900

rocketmq:
  name-server: localhost:9876
  producer:
    group: order
    max-message-size: 4096
    send-message-timeout: 3000
    retry-times-when-send-async-failed: 2


#---------自定义字段---------------------

oomall:
  external:
    customer-service:
      name: SimulatedCustomerServiceImpl
      version: 0.0.1-SNAPSHOT
    shop-service:
      name: SimulatedShopServiceImpl
      version: 0.0.1-SNAPSHOT
    inventory-service:
      name: SimulatedInventoryServiceImpl
      version: 0.0.1-SNAPSHOT
    freight-service:
      name: SimulatedFreightServiceImpl
      version: 0.0.1-SNAPSHOT
    discount-service:
      name: SimulatedDiscountServiceImpl
      version: 0.0.1-SNAPSHOT
    rebate-service:
      name: SimulatedRebateServiceImpl
      version: 0.0.1-SNAPSHOT
    shipment-service:
      name: SimulatedShipmentServiceImpl
      version: 0.0.1-SNAPSHOT
    share-service:
      name: SimulatedShareServiceImpl
      version: 0.0.1-SNAPSHOT
    activity-service:
      name: SimulatedActivityServiceImpl
      version: 0.0.1-SNAPSHOT
    flash-sale-service:
      name: SimulatedFlashSaleServiceImpl
      version: 0.0.1-SNAPSHOT
    seckill-service:
      name: SimulatedSeckillServiceImpl
      version: 0.0.1-SNAPSHOT
    goods-service:
      name: SimulatedGoodsServiceImpl
      version: 0.0.1-SNAPSHOT

  order:
    version: 0.0.1-SNAPSHOT
