server:
  port: 9900

spring:
  profiles:
    #active: dev

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  datasource:
    druid:
      url: jdbc:mysql://47.115.162.144:3306/oomall?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: OOMall
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
      test-while-idle: true

  cloud:
    nacos:
      server-addr: 47.115.162.144:8848

  application:
    name: oomall-order

management:
  endpoints:
    web:
      exposure:
        include: '*'

dubbo:
  application:
    name: dubbo-order
  scan:
    base-packages: cn.edu.xmu.oomall.service
  registry:
    address: nacos://47.115.162.144:8848
  protocol:
    name: dubbo
    host: localhost
    port: 19900

rocketmq:
  name-server: 47.115.162.144:9876
  producer:
    group: order
    max-message-size: 4096
    send-message-timeout: 3000
    retry-times-when-send-async-failed: 2


#---------自定义字段---------------------

oomall:
  external:
    customer-service:
      name: ChenCustomerServiceImpl
      version: 0.0.1-SNAPSHOT
    shop-service:
      name: WangShopServiceImpl
      version: 0.0.1-SNAPSHOT
    inventory-service:
      name: WangInventoryServiceImpl
      version: 0.0.1-SNAPSHOT
    freight-service:
      name: GoodaFreightServiceImpl
      version: 0.0.1-SNAPSHOT
    discount-service:
      name: WangDiscountServiceImpl
      version: 0.0.1-SNAPSHOT
    rebate-service:
      name: SimulatedRebateServiceImpl
      version: 0.0.1-SNAPSHOT
    shipment-service:
      name: SimulatedShipmentServiceImpl
      version: 0.0.1-SNAPSHOT
    share-service:
      name: SimulatedShareServiceImpl
      version: 0.0.1-SNAPSHOT
    activity-service:
      name: WangActivityServiceImpl
      version: 0.0.1-SNAPSHOT
    flash-sale-service:
      name: SongFlashSaleServiceImpl
      version: 0.0.1-SNAPSHOT
    seckill-service:
      name: GoodaSeckillServiceImpl
      version: 0.0.1-SNAPSHOT
    goods-service:
      name: WangGoodsServiceImpl
      version: 0.0.1-SNAPSHOT

  order:
    version: 0.0.1-SNAPSHOT

logging:
  level:
    cn.edu.xmu: info
