server:
  port: 9400

spring:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/oomall?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: gooda
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
      test-while-idle: true

  cloud:
    nacos:
      server-addr: localhost:8848

  application:
    name: oomall-payment

management:
  endpoints:
    web:
      exposure:
        include: '*'

dubbo:
  application:
    name: dubbo-payment
  scan:
    base-packages: cn.edu.xmu.oomall.service
  registry:
    address: nacos://localhost:8848
  protocol:
    name: dubbo
    port: 19400

oomall:
  external:
    payment-service:
      name: RebatePaymentImpl|SimplePaymentImpl
    order-service:
      name: SimulateOrderServiceImpl
    customer-service:
      name: SimulateCustomerServiceImpl
    afterSale-service:
      name: SimulateAfterSaleServiceImpl