server:
  port: 9400

spring:
  profiles:
    active: dev

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  datasource:
    druid:
      #url: jdbc:mysql://47.115.162.144:3306/oomall?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      url: jdbc:mysql://192.168.43.92:3306/oomall?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      #username: OOMall
      username: gooda
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
      test-while-idle: true

  cloud:
    nacos:
      server-addr: domi.xqchen.site:8848

  application:
    name: oomall-payment

management:
  endpoints:
    web:
      exposure:
        include: '*'

dubbo:
  application:
    name: dubbo-payment
  scan:
    base-packages: cn.edu.xmu.oomall.service
  registry:
    address: nacos://domi.xqchen.site:8848
    #address: nacos://47.115.162.144:8848
  protocol:
    name: dubbo
    port: 19400
    host: 192.168.43.123

oomall:
  external:
    payment-service:
      name: RebatePaymentImpl|SimplePaymentImpl
    order-service:
      name: SimulateOrderServiceImpl
      version: 0.0.1-SNAPSHOT
    customer-service:
      name: SimulateCustomerServiceImpl
      version: 0.0.1-SNAPSHOT
    afterSale-service:
      name: SimulateAfterSaleServiceImpl
      version: 0.0.1-SNAPSHOT

  payment:
    version: 0.0.1-SNAPSHOT

logging:
  level:
    cn.edu.xmu: info
